name: Build Cordova Android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/android-sdk

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Install Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Cordova & Android tools
      run: |
        npm install -g cordova@11
        mkdir -p $ANDROID_SDK_ROOT
        cd $ANDROID_SDK_ROOT
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline.zip
        unzip cmdline.zip -d cmdline-tools
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/ || true
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platform-tools" "platforms;android-33" "build-tools;33.0.2" "cmdline-tools;latest"
        export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin

    - name: Add Android platform
      run: |
        cordova platform add android@12.0.0

    - name: Build APK
      run: |
        cordova build android --release || cordova build android

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: |
          platforms/android/app/build/outputs/apk/debug/*.apk
          platforms/android/app/build/outputs/apk/release/*.apk
